spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848

#NamingService 配置属性
nacos:
  server-addr: 127.0.0.1:8848